const { AttachmentBuilder } = require("discord.js");

function formatTimestamp(date) {
  return new Date(date).toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });
}

async function generateTranscript(channel, ticket, guild) {
  const messages = [];
  let before = null;

  while (true) {
    const fetched = await channel.messages.fetch({
      limit: 100,
      ...(before ? { before } : {}),
    });
    if (!fetched.size) break;
    messages.push(...fetched.values());
    before = fetched.last().id;
    if (fetched.size < 100) break;
  }

  messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);

  const lines = [
    `Ticket #${ticket.ticketNumber} — ${guild.name}`,
    `${"=".repeat(40)}`,
    `Status   : ${ticket.status.toUpperCase()}`,
    `Category : ${ticket.categoryName || "None"}`,
    `Opened by: ${ticket.creatorId}`,
    `Opened at: ${formatTimestamp(ticket.openedAt)}`,
    ticket.closedAt ? `Closed at: ${formatTimestamp(ticket.closedAt)}` : null,
    ticket.closedById ? `Closed by: ${ticket.closedById}` : null,
    ticket.claimedById ? `Claimed by: ${ticket.claimedById}` : null,
    ticket.assistingStaffIds?.length
      ? `Assisting: ${ticket.assistingStaffIds.join(", ")}`
      : null,
    `Messages : ${messages.length}`,
    "",
  ].filter((l) => l !== null);

  if (ticket.answers?.length) {
    lines.push("--- Intake Questions ---");
    for (const a of ticket.answers) {
      lines.push(`Q: ${a.question}`);
      lines.push(`A: ${a.answer}`);
      lines.push("");
    }
  }

  lines.push("--- Messages ---");
  for (const msg of messages) {
    const ts = formatTimestamp(msg.createdAt);
    const author = msg.author.tag || msg.author.username;
    if (msg.content) {
      lines.push(`[${ts}] ${author}: ${msg.content}`);
    }
    for (const embed of msg.embeds) {
      const parts = ["[embed]"];
      if (embed.title) parts.push(`title: ${embed.title}`);
      if (embed.description) parts.push(`desc: ${embed.description}`);
      lines.push(`[${ts}] ${author} ${parts.join(" | ")}`);
    }
    for (const a of msg.attachments.values()) {
      lines.push(`[${ts}] ${author} [attachment: ${a.name}]: ${a.url}`);
    }
  }

  lines.push(
    "",
    `--- Generated by Ultimate Ticket Bot · ${formatTimestamp(new Date())} ---`,
  );

  const buffer = Buffer.from(lines.join("\n"), "utf-8");
  return new AttachmentBuilder(buffer, {
    name: `ticket-${ticket.ticketNumber}.txt`,
  });
}

module.exports = { generateTranscript };
